"""Local dashboard; no external scripts, trackers, or CDN dependencies."""

DASHBOARD_HTML = """<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lociqua</title><style>
:root{--n:#06285a;--t:#00aeb5;--i:#10213a;--m:#62708a;--l:#dce5ef;--b:#f5f8fb}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--i);font:15px system-ui,sans-serif}header{height:72px;background:#fff;border-bottom:1px solid var(--l);display:flex;align-items:center;gap:12px;padding:0 max(24px,calc((100vw - 1100px)/2))}header img{width:42px;height:42px}h1{font-size:19px;margin:0}main{max-width:1100px;margin:38px auto;padding:0 24px}.lead{color:var(--m);margin:0 0 25px}.grid{display:grid;grid-template-columns:3fr 2fr;gap:20px}.card{background:#fff;border:1px solid var(--l);border-radius:14px;padding:24px}h2{font-size:18px;margin:0 0 5px}.hint,.meta,.empty,.status{font-size:13px;color:var(--m)}label{display:block;font-weight:650;font-size:13px;margin:13px 0 6px}input,textarea{width:100%;font:inherit;padding:11px;border:1px solid #b9c7d8;border-radius:8px}textarea{min-height:85px;resize:vertical}button{cursor:pointer;background:var(--n);color:#fff;border:0;border-radius:8px;padding:11px 16px;font-weight:650;margin-top:16px}.tabs{display:flex;gap:7px;overflow:auto;border-bottom:1px solid var(--l);padding-bottom:9px;margin-top:20px}.tab{margin:0;background:#eef3f8;color:var(--i);white-space:nowrap;font-size:13px}.tab.active{background:var(--n);color:#fff}.result{padding:15px 0;border-top:1px solid var(--l)}.name{font-weight:700}.tag{display:inline-block;background:#dff7f6;color:#006d72;padding:3px 8px;border-radius:99px;margin:8px 3px 0 0;font-size:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style></head><body><header><img src="/assets/logo" alt="Lociqua"><h1>Lociqua</h1></header><main><h2>Search every location at once</h2><p class="lead">Each location loads independently in its own result tab.</p><section class="grid"><article class="card"><h2>Multi-location search</h2><p class="hint">Search authorized records already imported into this local database.</p><form id="search"><label>Keyword<input id="keyword" required placeholder="e.g. AI, dentist, manufacturing"></label><label>Locations — one per line<textarea id="locations" required placeholder="Baner&#10;Hinjewadi&#10;Kharadi"></textarea></label><label>Results per location<input id="limit" type="number" min="1" max="100" value="5"></label><button>Search all locations</button></form><div id="tabs" class="tabs" hidden></div><div id="results"></div></article><aside class="card"><h2>Import CSV</h2><p class="hint">Requires a UTF-8 <code>name</code> column.</p><form id="upload"><input id="file" type="file" accept=".csv,text/csv" required><button>Import data</button></form><p id="import-status" class="status"></p></aside></section></main><script>
const box=document.querySelector('#results'),tabs=document.querySelector('#tabs');let groups={};const esc=x=>{const e=document.createElement('div');e.textContent=x||'';return e.innerHTML};
document.querySelector('#upload').onsubmit=async e=>{e.preventDefault();const s=document.querySelector('#import-status'),f=document.querySelector('#file').files[0];s.textContent='Importing...';try{const r=await fetch('/api/import/csv',{method:'POST',body:f,headers:{'X-Source-Name':f.name}}),d=await r.json();if(!r.ok)throw Error(d.error.message);s.textContent='Imported '+d.accepted+' records.'}catch(x){s.textContent='Import failed: '+x.message}};
function show(location){[...tabs.children].forEach(b=>b.classList.toggle('active',b.dataset.location===location));const s=groups[location];if(s.loading){box.innerHTML='<p class="empty">Searching '+esc(location)+'...</p>';return}if(s.error){box.innerHTML='<p class="empty">Search failed: '+esc(s.error)+'</p>';return}box.innerHTML=s.results.length?s.results.map(c=>`<article class="result"><div class="name">${esc(c.name)}</div><div class="meta">${esc([c.locality,c.city,c.country].filter(Boolean).join(' · '))}</div>${c.categories.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</article>`).join(''):'<p class="empty">No matching records in '+esc(location)+'.</p>'}
document.querySelector('#search').onsubmit=e=>{e.preventDefault();const keyword=document.querySelector('#keyword').value,limit=Number(document.querySelector('#limit').value),locations=[...new Set(document.querySelector('#locations').value.split(/[\\n,]+/).map(x=>x.trim()).filter(Boolean))];groups={};tabs.innerHTML='';tabs.hidden=!locations.length;locations.forEach((location,index)=>{groups[location]={loading:true,results:[]};const b=document.createElement('button');b.className='tab';b.dataset.location=location;b.textContent=location+' · loading';b.onclick=()=>show(location);tabs.append(b);if(!index)show(location);fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({queries:[{keyword,location,max_results:limit,provider_preference:['local_database']}]})}).then(r=>r.json().then(d=>({r,d}))).then(({r,d})=>{if(!r.ok)throw Error(d.error.message);groups[location]={loading:false,results:d.results};b.textContent=location+' · '+d.results_count+' found';if(b.classList.contains('active'))show(location)}).catch(x=>{groups[location]={loading:false,results:[],error:x.message};b.textContent=location+' · error';if(b.classList.contains('active'))show(location)})})};
</script></body></html>"""
