"""Dependency-free browser dashboard served by the Lociqua API."""

DASHBOARD_HTML = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Lociqua</title>
<style>
:root{color-scheme:light;font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#132033;background:#f2f5f9}body{max-width:1120px;margin:auto;padding:26px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h1{margin:0;color:#08285e}.card{background:#fff;border:1px solid #dce4ee;border-radius:12px;padding:18px;margin:14px 0;box-shadow:0 1px 2px #1020400c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:12px}.record{border-left:4px solid #0b62d6;padding:10px;background:#f8fbff;margin:8px 0}input,textarea,select,button{box-sizing:border-box;width:100%;padding:9px;margin:5px 0;border:1px solid #bdc9d8;border-radius:7px;font:inherit}button{cursor:pointer;background:#0b55bb;color:#fff;border:0;font-weight:650}button.secondary{background:#e8eef7;color:#14223a}button.danger{background:#a12828}.toolbar{display:flex;flex-wrap:wrap;gap:8px}.toolbar button{width:auto}.muted{color:#59677a;font-size:.92em}pre{white-space:pre-wrap;overflow:auto;background:#081a34;color:#dcedff;padding:12px;border-radius:8px}.hidden{display:none}.notice{padding:10px;background:#fff5cc;border-radius:7px}
</style>
<body><header><div><h1>Lociqua</h1><div class="muted">Authorized business-data operations</div></div><button id="signout" class="secondary hidden" onclick="signout()">Sign out</button></header>
<section class="card" id="login"><h2>Sign in</h2><div class="grid"><label>Email<input id="email" autocomplete="email" type="email"></label><label>Password<input id="password" autocomplete="current-password" type="password"></label></div><button onclick="signin()">Sign in</button><p id="msg" class="notice hidden"></p></section>
<main id="app" class="hidden">
<section class="card"><div class="toolbar"><button onclick="view('search')">Search</button><button onclick="view('import')">Import</button><button onclick="research()">Research sessions</button><button onclick="evidence()">Evidence review</button><button onclick="duplicates()">Duplicate review</button><button onclick="quality()">Quality</button><button onclick="sources()">Sources</button><button onclick="policies()">Source policies</button><button onclick="saved()">Saved searches</button><button class="secondary" onclick="extensionToken()">Extension token</button><button id="adminButton" class="hidden" onclick="members()">Administration</button><button class="secondary" onclick="exportCsv()">Export CSV</button></div></section>
<section id="searchView" class="card"><h2>Search locations</h2><div class="grid"><label>Keyword<input id="keyword" placeholder="e.g. dentist"></label><label>Locations<textarea id="locations" placeholder="One location per line, e.g. Pune"></textarea></label></div><button onclick="search()">Search</button><div id="results"></div></section>
<section id="importView" class="card hidden"><h2>Import authorized CSV</h2><p class="muted">Only import data you own or are permitted to use. A UTF-8 CSV needs a <code>name</code> column.</p><input id="file" type="file" accept=".csv,text/csv"><button onclick="upload()">Import CSV</button></section>
<section id="utilityView" class="card hidden"><h2 id="utilityTitle">Details</h2><div id="utility"></div></section>
</main>
<script>
let token=sessionStorage.lociqua||'', userRole=sessionStorage.lociquaRole||'', lastResults=[];
const $=id=>document.getElementById(id), headers=()=>({Authorization:'Bearer '+token});
function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}
function text(node,value){node.textContent=value==null?'':String(value)}
function showMessage(value){let n=$('msg');text(n,value);n.classList.remove('hidden')}
async function api(path,options={}){let response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});let type=response.headers.get('content-type')||'';let data=type.includes('json')?await response.json():await response.text();if(!response.ok)throw new Error(data.error?data.error.message:response.statusText);return data}
function activate(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('signout').classList.remove('hidden');if(userRole==='owner')$('adminButton').classList.remove('hidden');view('search') }
async function signin(){try{let response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});let data=await response.json();if(!response.ok)throw new Error(data.error.message);token=data.access_token;userRole=data.role;sessionStorage.lociqua=token;sessionStorage.lociquaRole=userRole;activate()}catch(error){showMessage(error.message)}}
function signout(){sessionStorage.removeItem('lociqua');sessionStorage.removeItem('lociquaRole');location.reload()}
function view(name){['searchView','importView','utilityView'].forEach(id=>$(id).classList.add('hidden'));$(name+'View').classList.remove('hidden')}
function utility(title){view('utility');text($('utilityTitle'),title);clear($('utility'));return $('utility')}
function record(parent,label,value){let row=document.createElement('div');row.className='record';let strong=document.createElement('strong');text(strong,label);row.append(strong,document.createTextNode(' '+(value||'—')));parent.append(row)}
async function search(){let locations=$('locations').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(!$('keyword').value.trim()||!locations.length)return alert('Enter a keyword and at least one location.');try{let data=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({queries:locations.map(location=>({keyword:$('keyword').value.trim(),location,max_results:25}))})});lastResults=data.results||[];let target=$('results');clear(target);if(!lastResults.length){record(target,'No matching records','Import authorized data or use another query.');return}lastResults.forEach(company=>{let row=document.createElement('div');row.className='record';let button=document.createElement('button');button.className='secondary';text(button,company.name+' — '+(company.city||company.locality||'unknown location'));button.onclick=()=>detail(company.id);row.append(button);let p=document.createElement('p');p.className='muted';text(p,(company.categories||[]).join(', ')+' · '+(company.website||'no website'));row.append(p);target.append(row)})}catch(error){alert(error.message)}}
async function detail(id){try{let data=await api('/api/companies/'+encodeURIComponent(id));let target=utility('Company quality, provenance, evidence, and audit history');record(target,'Company',data.company.name);record(target,'Quality score',data.quality.score+'/100');record(target,'Missing fields',(data.quality.missing_fields||[]).join(', ')||'None');record(target,'Approved evidence',data.quality.approved_evidence||0);let prov=document.createElement('pre');text(prov,JSON.stringify({source_records:data.company.sources,field_provenance:data.field_provenance,evidence:data.evidence,audit_events:data.audit_events},null,2));target.append(prov)}catch(error){alert(error.message)}}
async function upload(){let f=$('file').files[0];if(!f)return alert('Choose a CSV file first.');try{let data=await api('/api/import/csv',{method:'POST',headers:{'X-Source-Name':f.name},body:f});let target=utility('Import result');record(target,'Accepted',data.accepted);record(target,'Rejected',data.rejected);if(data.errors&&data.errors.length)record(target,'Errors',data.errors.join('; '))}catch(error){alert(error.message)}}
function reviewCard(target,review,actions){let box=document.createElement('div');box.className='record';record(box,'Decision state',review.status);record(box,'Candidate score',review.score+'/100');record(box,'Reasons',(review.reasons||[]).join(', '));record(box,'Left record',review.left_company.name+' — '+(review.left_company.city||''));record(box,'Right record',review.right_company.name+' — '+(review.right_company.city||''));if(review.reviewer_email)record(box,'Reviewer',review.reviewer_email);if((review.audit_events||[]).length)record(box,'Audit event',review.audit_events[0].action+' · '+review.audit_events[0].occurred_at);if(actions){let buttons=document.createElement('div');buttons.className='toolbar';['approved','rejected'].forEach(status=>{let b=document.createElement('button');text(b,status==='approved'?'Approve match':'Reject match');b.className=status==='rejected'?'secondary':'';b.onclick=()=>reviewDecision(review.id,status);buttons.append(b)});box.append(buttons)}target.append(box)}
async function duplicates(){try{let results=await Promise.all([api('/api/duplicates?status=pending'),api('/api/duplicates?status=approved'),api('/api/duplicates?status=rejected')]);let target=utility('Duplicate review queue');let pending=results[0].reviews;if(!pending.length)record(target,'Pending queue','No pending reviews.');pending.forEach(review=>reviewCard(target,review,true));let history=[...results[1].reviews,...results[2].reviews];if(history.length){let heading=document.createElement('h3');text(heading,'Recent decisions');target.append(heading);history.forEach(review=>reviewCard(target,review,false))}}catch(error){alert(error.message)}}
async function reviewDecision(id,status){if(!confirm((status==='approved'?'Approve':'Reject')+' this review? Companies will not be merged or deleted.'))return;try{await api('/api/duplicates/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});duplicates()}catch(error){alert(error.message)}}
async function quality(){try{let data=await api('/api/companies?quality=low&limit=100');let target=utility('Low-quality records');if(!data.companies.length)record(target,'Quality','No records below the current 60/100 threshold.');data.companies.forEach(c=>{let b=document.createElement('button');b.className='secondary';text(b,c.name+' — '+c.quality.score+'/100 · missing: '+c.quality.missing_fields.join(', '));b.onclick=()=>detail(c.id);target.append(b)})}catch(error){alert(error.message)}}
async function sources(){try{let data=await api('/api/sources');let target=utility('Source registry');data.sources.forEach(source=>record(target,source.name,source.source_type+' · '+source.permission_basis))}catch(error){alert(error.message)}}
async function policies(){try{let data=await api('/api/source-policies');let target=utility('Approved source policies');if(userRole==='owner'){let create=document.createElement('button');text(create,'Create browser-capture policy');create.onclick=()=>createPolicy();target.append(create)}data.source_policies.forEach(item=>record(target,item.name,item.domain+' · '+item.connector_type+' · '+item.status+' · export '+(item.export_allowed?'allowed':'blocked')));let hint=document.createElement('p');hint.className='muted';text(hint,'Capture is denied until an owner approves a browser_capture policy for the domain.');target.prepend(hint)}catch(error){alert(error.message)}}
async function createPolicy(){let name=prompt('Policy name');let domain=prompt('Approved domain, for example directory.example.com');let permission_basis=prompt('Permission basis, licence, or contract reference');if(!name||!domain||!permission_basis)return;try{await api('/api/source-policies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,domain,permission_basis,connector_type:'browser_capture',status:'approved',allowed_fields:['name','website','phone','address','city','description'],export_allowed:confirm('Allow exports of records supported by this source?')})});policies()}catch(error){alert(error.message)}}
async function evidence(){try{let data=await api('/api/evidence?status=pending');let target=utility('Evidence review queue');if(!data.evidence.length)record(target,'Pending evidence','No evidence is waiting for review.');data.evidence.forEach(item=>{let box=document.createElement('div');box.className='record';record(box,item.policy_name,item.capture_domain+' · '+item.status);record(box,'Captured fields',Object.keys(item.captured_fields||{}).join(', '));record(box,'URL',item.capture_url);if(userRole!=='viewer'){['approved','rejected','needs_correction','stale'].forEach(status=>{let b=document.createElement('button');b.className=status==='approved'?'':'secondary';text(b,status.replace('_',' '));b.onclick=()=>evidenceDecision(item.id,status);box.append(b)})}target.append(box)})}catch(error){alert(error.message)}}
async function evidenceDecision(id,status){try{await api('/api/evidence/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});evidence()}catch(error){alert(error.message)}}
async function research(){try{let data=await api('/api/research-sessions');let target=utility('Research sessions');if(userRole!=='viewer'){let create=document.createElement('button');text(create,'Create research session');create.onclick=()=>createResearch();target.append(create)}if(!data.research_sessions.length)record(target,'Research sessions','Create one for a keyword and one or more locations.');data.research_sessions.forEach(session=>{let box=document.createElement('div');box.className='record';record(box,session.title,session.keyword+' · '+session.status);(session.tasks||[]).forEach(task=>record(box,task.location,task.status));target.append(box)})}catch(error){alert(error.message)}}
async function createResearch(){let title=prompt('Session title');let keyword=prompt('Keyword');let locations=prompt('Locations, separated by commas');if(!title||!keyword||!locations)return;try{await api('/api/research-sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,keyword,target_locations:locations.split(',').map(x=>x.trim()).filter(Boolean)})});research()}catch(error){alert(error.message)}}
async function extensionToken(){try{let data=await api('/api/auth/extension-token',{method:'POST'});prompt('Copy this 10-minute extension token. Do not share it.',data.access_token)}catch(error){alert(error.message)}}
async function saved(){try{let data=await api('/api/saved-searches');let target=utility('Saved searches');data.saved_searches.forEach(item=>record(target,item.name,item.keyword+' · '+(item.location||'all locations')))}catch(error){alert(error.message)}}
async function members(){try{let data=await api('/api/members');let target=utility('Workspace administration');let form=document.createElement('div');form.className='grid';form.innerHTML='<label>Email<input id="memberEmail" type="email"></label><label>Initial password<input id="memberPassword" type="password"></label><label>Role<select id="memberRole"><option>viewer</option><option>editor</option><option>owner</option></select></label>';target.append(form);let add=document.createElement('button');text(add,'Create or add user');add.onclick=()=>addMember();target.append(add);data.members.forEach(member=>{let row=document.createElement('div');row.className='record';record(row,member.email,member.role);let select=document.createElement('select');['viewer','editor','owner'].forEach(role=>{let o=document.createElement('option');o.value=role;text(o,role);if(role===member.role)o.selected=true;select.append(o)});let change=document.createElement('button');text(change,'Change role');change.onclick=()=>memberUpdate(member.id,{role:select.value});let revoke=document.createElement('button');revoke.className='danger';text(revoke,'Revoke access');revoke.onclick=()=>memberUpdate(member.id,{action:'remove'});row.append(select,change,revoke);target.append(row)})}catch(error){alert(error.message)}}
async function addMember(){try{await api('/api/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('memberEmail').value,password:$('memberPassword').value,role:$('memberRole').value})});members()}catch(error){alert(error.message)}}
async function memberUpdate(id,body){if(!confirm('Apply this access change?'))return;try{await api('/api/members/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});members()}catch(error){alert(error.message)}}
async function exportCsv(){try{let response=await fetch('/api/companies/export?keyword='+encodeURIComponent($('keyword').value),{headers:headers()});if(!response.ok){let d=await response.json();throw new Error(d.error.message)}let a=document.createElement('a');a.href=URL.createObjectURL(await response.blob());a.download='lociqua-export.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(error){alert(error.message)}}
if(token)activate();
</script></body></html>'''
